// lib/templates/index.ts

export const templates = [
  {
    id: "landscape_3col_maths",
    name: "Landscape 3 columns (Maths)",
    format: "latex",
    sourcePath: "lib/templates/latex/landscape_3col_maths.tex",
    publicPath: "/templates/landscape_3col_maths.tex",
    previewPath: "/templates/previews/3cols_landscape_Template_Calculus.pdf",
    thumbnailPath: "/templates/previews/3cols_landscape.png",
    description: "Compact 3-column landscape layout ideal for math formulas.",
  },
  {
    id: "2cols_portrait",
    name: "Portrait 2 columns (QFT/QED cheat-sheet)",
    format: "latex",
    sourcePath: "lib/templates/latex/2cols_portrait.tex",
    publicPath: "/templates/2cols_portrait.tex",
    thumbnailPath: "/templates/previews/2cols_portrait.png",
    description: "Classic 2-column portrait layout for physics summaries.",
  },
  {
    id: "cornell",
    name: "Cornell Notes System",
    format: "latex",
    sourcePath: "lib/templates/latex/cornell.tex",
    publicPath: "/templates/cornell.tex",
    previewPath: "/templates/previews/cornell.pdf",
    thumbnailPath: "/templates/previews/cornell.png",
    description: "Guided note-taking with Cues and Summary sections.",
  },
  {
    id: "problem_solving",
    name: "Problem Solving Sheet (STEM)",
    format: "latex",
    sourcePath: "lib/templates/latex/problem_solving.tex",
    publicPath: "/templates/problem_solving.tex",
    previewPath: "/templates/previews/problem_solving.pdf",
    thumbnailPath: "/templates/previews/problem_solving.png",
    description: "Structured blocks for Engineering/Physics exercises.",
  },
  {
    id: "zettelkasten",
    name: "Zettelkasten Cards",
    format: "latex",
    sourcePath: "lib/templates/latex/zettelkasten.tex",
    publicPath: "/templates/zettelkasten.tex",
    previewPath: "/templates/previews/zettelkasten.pdf",
    thumbnailPath: "/templates/previews/zettelkasten.png",
    description: "Knowledge cards grid layout for modular thinking.",
  },
] as const;